"""empty message

Revision ID: ca5affe72bc5
Revises: 
Create Date: 2018-05-10 21:19:51.621560

"""
from alembic import op
import sqlalchemy as sa

from app.extentions import bcrypt

# revision identifiers, used by Alembic.
revision = 'ca5affe72bc5'
down_revision = None
branch_labels = None
depends_on = None


def seed():
    user_table = sa.sql.table(
        'users',
        sa.sql.column('email', sa.String),
        sa.sql.column('email_confirmed', sa.Boolean),
        sa.sql.column('name', sa.String),
        sa.sql.column('role', sa.Enum),
        sa.sql.column('_password', sa.String),
    )
    op.bulk_insert(user_table, [
        {
            'id': 1,
            'email': 'anjingcuc@gmail.com',
            'email_confirmed': True,
            'name': 'anjing',
            'role': 'ADMIN',
            '_password': bcrypt.generate_password_hash('ZB73QdC7sa9D3i9l')
        },
    ])


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('email_confirmed', sa.Boolean(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column(
            'role', sa.Enum('ADMIN', 'USERS', name='userrole'),
            nullable=False),
        sa.Column('_password', sa.String(length=128), nullable=False),
        sa.Column('created_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        mysql_collate='utf8_general_ci')
    # ### end Alembic commands ###
    seed()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
